print("Welcome to the ti calculator!")
bill = float(input("What was the total bill amount? "))
tip = float(input("What percentage tip would you like to give? "))
split = float(input("How many people to split the bill? "))
print(f"Each person should pay: ${bill*(1 + tip/100)/split:.2f}")